apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv-sw
spec:
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}